[project]
name = "Sola"
version = "1.3"
description = "Created by Krish to Automate Form-16 Generation using ITR Format. Created for POOJA ITR CENTER"
readme = "README.md"
requires-python = ">=3.9"
authors = [
    { name = "Krishna Noutiyal"}
]
dependencies = [
  "flet","openpyxl","pandas"
]

[tool.flet]
product = "Sola"
company = "Pooja ITR Center"
copyright = "Copyright (C) 2025 Pooja ITR Center"
